import * as core from '../../../core';

export const GetFieldsRequestProperties = {
  FieldId: 'Field Id',
  Mnemonic: 'Mnemonic',
  Title: 'title',
  DlCommercialModelCategory: 'dlCommercialModelCategory',
  Category: 'category',
  Description: 'description',
  YkCommodity: 'YK: Commodity',
  YkEquity: 'YK: Equity',
  YkMunicipal: 'YK: Municipal',
  YkPreferred: 'YK: Preferred',
  YkMoneyMarket: 'YK: Money Market',
  YkUsGovernment: 'YK: US Government',
  YkCorporate: 'YK: Corporate',
  YkIndex: 'YK: Index',
  YkCurrency: 'YK: Currency',
  YkMortgage: 'YK: Mortgage',
  StandardWidth: 'Standard Width',
  StandardDecimalPlaces: 'Standard Decimal Places',
  FieldType: 'Field Type',
  DlBulk: 'DL:Bulk',
  DlExtendedBulk: 'DL: Extended Bulk',
  Created: 'Created',
  CurrentMaximumWidth: 'currentMaximumWidth',
  Bval: 'bval',
  BvalBlocked: 'bvalBlocked',
  GetFundamentals: 'getFundamentals',
  DlAvailableInGetHistory: 'dlAvailableInGetHistory',
  GetCompany: 'getCompany',
  OldMnemonic: 'Old Mnemonic',
  DlCategory: 'DL Category',
  PsboOpt: 'psboOpt',
  DsBvalMetered: 'dsBvalMetered',
  DlBoOptFundamentals: 'dlBoOptFundamentals',
  DlBoOptBdvd: 'dlBoOptBdvd',
  DlBoOptBest: 'dlBoOptBest',
  DlBoOptCreditRisk: 'dlBoOptCreditRisk',
  DlBoOptCapStruct: 'dlBoOptCapStruct',
  DlBoOptCreditRiskGetCompany: 'dlBoOptCreditRiskGetCompany',
  DlBoOptCapStructGetCompany: 'dlBoOptCapStructGetCompany',
  SapiNewSecuritySetup: 'SAPI New Security Setup',
  DlBoOptRegCompliance: 'dlBoOptRegCompliance',
  DlBoOptIssuerRatings: 'dlBoOptIssuerRatings',
  XsdType: 'xsd:type',
  XsdMinInclusive: 'xsd:minInclusive',
  XsdMaxInclusive: 'xsd:maxInclusive',
  XsdMinExclusive: 'xsd:minExclusive',
  XsdMaxExclusive: 'xsd:maxExclusive',
  XsdFractionDigits: 'xsd:fractionDigits',
  XsdMinLength: 'xsd:minLength',
  XsdMaxLength: 'xsd:maxLength',
  XsdLength: 'xsd:length',
  XsdPattern: 'xsd:pattern',
  RdfLangString: 'rdf:langString',
  Iri: 'IRI',
  SuperPropertyIri: 'SuperPropertyIRI',
  IsAbstract: 'Is Abstract',
  Identifier: 'identifier',
  NPort: 'nPort',
  DlActualsOrEstimates: 'DL:Actuals or Estimates',
  DlAdjustedFinancialsAvailable: 'DL Adjusted Financials Available',
  DataLicense: 'Data License',
  PlatformStatic: 'Platform: Static',
  PlatformStreaming: 'Platform: Streaming',
  PlatformTerminalRequired: 'Platform: Terminal Required',
  DlActualsAvailable: 'DL Actuals Available',
  DlEstimatesAvailable: 'DL Estimates Available',
  LoadingSpeed: 'Loading Speed',
  Range: 'Range',
  Retired: 'retired',
  BulkSchema: 'bulkSchema',
} as const;

export type GetFieldsRequestProperties =
  (typeof GetFieldsRequestProperties)[keyof typeof GetFieldsRequestProperties];

export const getFieldsRequestProperties = core.cast.identity<GetFieldsRequestProperties>();
